name: EDA CI/CD Pipeline

on:
  push:
    branches:  
      - task1 # Trigger on pushes to the main branch
  pull_request:
    branches:   
      - task1 # Trigger on pull requests targeting the main branch

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
        
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'  # Specify the Python version to use

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt  # Install dependencies from requirements.txt

      - name: Run EDA Script
        run: |
          python eda.py  # Execute your EDA script
          
      - name: Upload Results
        if: always()  # Ensure this step runs even if previous steps fail
        uses: actions/upload-artifact@v3
        with:
          name: eda-results
          path: |
            results/  # Path to the directory where script saves results
